# render.yaml
services:
  - type: web
    name: mktv5-render
    env: node
    plan: free
    region: oregon
    healthCheckPath: /api/health
    build:
      apt:
        packages:
          - libnss3
          - libatk-bridge2.0-0
          - libcups2
          - libgtk-3-0
          - libxkbcommon0
          - libxss1
          - libasound2
          - libgbm1
          - chromium-browser
    # ✅ CORREÇÃO DEFINITIVA APLICADA AQUI
    buildCommand: "rm -rf node_modules package-lock.json && npm install && npm run build"
    startCommand: "npm run migrate:deploy && npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: mktv5-render-db
          property: connectionString
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/chromium-browser
      # Adicione aqui as outras variáveis que corrigimos (APP_BASE_URL, etc.)

databases:
  - name: mktv5-render-db
    plan: free
    databaseName: mktv5render
    user: mktv5renderuser
    region: oregon
